export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const SAVE_EDITED_POST = 'SAVE_EDITED_POST';
export const ADD_POST = 'ADD_POST';
export const SET_AUTHORIZED = 'SET_AUTHORIZED';
export const DELETE_POST = 'DELETE_POST';